### ISSUE TITLE
disable writable running capability in netopeer-GUI

### ISSUE THREAD

**Issue by sameeralirock** [CESNET/Netopeer-GUI#96]
Hi Team Netopeer.

There is a difference that was observed while committing any config through netopeer-CLI and GUI, while the GUI expects writable-running capability as one of the criteria for committing the changes the same is not required in CLI.
Due to this reason we're not able to commit the config through netopeer-gui as our server doesnt support writable-running capability, but same thing when tried with netopeer-cli we're able to commit changes after edit-config from candidate to running database.
Can there be a runtime attribute in some config file that allows to enable/disable writable-running capability in the client side of Netopeer-GUI.

Please help us out in this;
TIA

**Comment by alexadavid** [comment]
Hello,
which version of GUI are you using? If you are using demo, the problem was discussed in #85 and fixed in master branch. To update the code, please try to do these commands:

1) cd /var/www/netopeer-gui/
2) git pull origin master
3) rm /var/www/netopeer-gui/app/netopeerWebGui.db
4) php composer.phar install

**Comment by sameeralirock** [comment]
Thanks Alex,

I did the same thing but I think the issue is with placement of datamodels, can you please suggest guideline to add datamodels in netopeer-GUI.

**Comment by alexadavid** [comment]
NetopeerGUI supports only datamodels available from <get-schema> operation
